name: DevOps CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Compilación y Pruebas Unitarias
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Ejecutar Pruebas Unitarias con Maven
        run: mvn clean test

  sonar-analysis:
    name: Análisis de Calidad y Seguridad (SonarCloud)
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Analizar Código en SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=ingenieria-devops -Dsonar.projectKey=springboot-app-devops -Dsonar.qualitygate.wait=true